language: python

arch:
  - amd64
  - ppc64le

python:
  - "3.8"
  - "3.9"
  - "3.10"

env:
  - DJANGO_VERSION="4.0"

install:
  - pip install -r devrequirements_${DJANGO_VERSION}.txt

script: python runtests.py

before_deploy:
  - pip install wheel
  - python setup.py sdist bdist_wheel

deploy:
  provider: pypi
  user: bryanhelmig
  password:
    secure: amY+WgU7S4RD/8S4rDz6/Gso1bucyqWWdCfG5RXHxD1mBcOIBjfiVmDkbiOxODany3KS5Hmo3mvXjOlpgmhuxw2iWdG1o059pMh8PH7I2WwHTliUSGwIshFIUmAivrh1mq9qUsHfsGpPow3AaxFB7G/FnrAQjedTTGYfN5ZnI/k=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    repo: zapier/django-rest-hooks
